# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application build and release

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: research-mnemonic
          - os: windows-latest
            artifact_name: research-mnemonic.exe
          - os: macos-latest
            artifact_name: research-mnemonic

    permissions:
      contents: write
      packages: write 

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Setup pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies with Pipenv
        run: |
          pipenv install --dev

      - name: Create Package
        run: |
          pipenv run pyinstaller research-mnemonic.spec
      
      - name: Rename packages
        run: |
          ls -al
          pwd
          if [ "$RUNNER_OS" == "Linux" ]; then
            mv dist/${{ matrix.artifact_name }} dist/${{ matrix.artifact_name }}_Linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            mv dist/${{ matrix.artifact_name }} dist/${{ matrix.artifact_name }}_Windows.exe
          elif [ "$RUNNER_OS" == "Mac" ]; then
            mv dist/${{ matrix.artifact_name }} dist/${{ matrix.artifact_name }}_Mac
          fi
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/

