# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Setup pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Install Dependencies with Pipenv
      run: |
        pipenv install --dev
    
    - name: Install Pywin32 if on windows
      run: |
         if [ "$RUNNER_OS" == "Windows" ]; then
          pipenv install pywin32
         fi
      shell: bash
         
    - name: Create Package
      run: |
        pipenv run pyinstaller research-mnemonic.spec
