# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests using pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Setup pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install Dependencies with Pipenv
        run: |
          pipenv install --dev

      - name: Test with pytest
        run: |
          pipenv run pytest
